/*The array holds more detailed information to be displayed for each of the resume categories*/
let information = {
    Bio: "<p class='p-5' style='color:black; font-family:Verdana, Geneva, Tahoma, sans-serif;'>I am Luke, I am a web development student in Cape Town. I am studying Web Development through Hyperion Dev, currently set to complete in November 2022. I currently hold a degree in Architecture from UCT and have over 3 years experience working abroad in education.<br> I have always been passionate about the combination of technology and design, which has motivated me to pursue and complete my degree in Architecture. Throughout my studies I have developed capabilities of problem solving, visual design, and teamwork. I believe there are also  fundamental overlaps with web development,  as functionality and appearance or usability have to be considered in like regard.<br> I have also had the privilege of acting as an educator and student abroad and I attribute an incredible motivation for learning and self study to this experience. I achieved an N4 certification whilst working full time and I will be completing my intermediate certification in Japanese by the end of this year. As the range of knowledge required in web development is largely filled through circumstances of necessity, self-study and research is an ability in which I am proud to be capable.</p>",
    Skills: "<ul><hr><li class='fs-6 text-center'>Coding experience and skills include:</li><hr><li><h3>HTML<h3></li><li><h3>CSS<span class='fs-6' style='color:black; font-family:Verdana, Geneva, Tahoma, sans-serif;'>, with practical knowledge of the <b><a target='_' href='https://getbootstrap.com/' class='text-decoration-none'>Bootstrap</a></b> framework</span></h3></li><li><h3>Javascript<span class='fs-6' style='color:black; font-family:Verdana, Geneva, Tahoma, sans-serif;'>, with practical knowledge of <b><a target='_' href='https://jquery.com/' class='text-decoration-none'>JQuery</a></b></span></h3></li><hr><li class='fs-6 text-center'>Additional softwares for visual representation include:</li><hr><li class='fs-4'><a target='_' href='https://tinyurl.com/u6dfhv8u'class='text-decoration-none'>Adobe Photoshop</a>,<span class='fs-6'> for editting and adjusting photographs and pictures</span></li><li class='fs-4'><a target='_' href='https://inkscape.org/'class='text-decoration-none'>Inkscape</a>, <span class='fs-6'>an open source program that can be used to create and edit scalable vetor graphics</span></li><li class='fs-4'><a target='_' href='https://tinyurl.com/4w4en7kj' class='text-decoration-none'> Autodesk AutoCad</a>,<span class='fs-6'> an advanced software that can be used for creating scaled 2D drawings and plans</span></li><li class='fs-4'><a target='_' href='https://www.sketchup.com/' class='text-decoration-none'>Trimble Sketchup</a>,<span class='fs-6'> 3D design and modelling software</span></li><li class='fs-4'><a target='_' href='https://tinyurl.com/4zcaf7yr' class='text-decoration-none'>Black Magic DaVinci Resolve</a>, <span class='fs-6'>advanced film and video editting software</span></li><hr>Soft skills include:<br>Critical thinking, Organization, Visual Representation, and Communication.",
    Education: "<hr><h3 class='text-center'><a target='_' href='https://www.hyperiondev.com/' class='text-decoration-none'>Hyperion Dev</a></h3><h4 class='text-center'>May 2022 till November 2022</h4><hr><p class='fs-6'>The Full Stack web development course at Hyperion Dev is an intensive 6 month program. Covering the MERN stack with multiple Capstone projects and a focus on industry standard workflow.<br>I studied online through the Cape Town location.</p><hr><h3 class='text-center'><a target='_'href='http://www.apg.uct.ac.za/' class='text-decoration-none'>University of Cape Town</a></h3><h4 class='text-center'>February 2015 till April 2018</h4><hr><p class='fs-6'>The Architecture program at UCT covers design, practical mathematics, building technology, environmental services, history and theory of design.<br> I studied for 3 years at the UCT school of Architecture, in Cape Town.</p><hr><h3 class='text-center'><a target='_' href='https://architecture.mandela.ac.za/' class='text-decoration-none'>Nelson Mandela Metropolitan University</a></h3><h4 class='text-center'>February 2014 till November 2014</h4><hr><p class='fs-6'>The Architecture Course at NMMU covers design, design history, structures and maths, surveying, building technology, computer aided design.<br> I studied for 1 year at the NMMU school of Architecture, in Port Elizabeth.</p><hr><h3 class='text-center'><a target='_' href='https://somersetcollege.org/' class='text-decoration-none'>Somerset College High School</a></h3><h4 class='text-center'>January 2009 till December 2013</h4><hr><p class='fs-6'>An IEB syllabus highschool located in Stellenbosch. I matriculated here in 2013.</p>",
    'Work Experience': "<hr><h3 class='text-center'><a target='_'href='https://bec-i-cube.com/?fbclid=IwAR0XDHKKmrWQyIdVrgBY7yoDAEf9KiW5eyu4H9SfL66renIGZfJhVI3og8Q' class='text-decoration-none' >Bright English Club's ICube and EEI</a></h3><h4 class='text-center'>2021 March - 2022 April</h4><hr><p class='fs-6'>BEC ICube and EEI are programs aimed at elementary through highschool students in Saitama, Japan. They cover natural and social sciences as well as maths, through lessons, demonstrations and research projects conducted exclusively in English.<br>I worked here in the capacity of teacher and curriculm planner. Responsibilities included: Preparing lessons and content, delivering lessons, organizing and conducting demonstrations, preparation and delivery of online lessons, working as part of a team to plan events and year curriculums.</p><hr><h3 class='text-center'>California Language Institute</h3><h4 class='text-center'>2021 March - 2022 April</h4><hr><p class='fs-6'>English program for elementary and pre-elementary school students in Tokyo, Japan.<br>I worked here in the capacity of teacher. Responsibilities included, preparation and delivery of lessons, student assesments, teacher training, administration of several different schools, meetings and discussions with parents.</p><hr><h3 class='text-center'>Kyounghee E'mares</h3><h4 class='text-center'>2018 July - 2019 February</h4><hr><p class='fs-6'>Private English academy for pre-elementary school students in Ulsan, South Korea. <br>I worked here in the capacity of teacher. Responsibilities included: delivery of lessons, preparation and planning for events.</p>",
    Projects: "<hr><h3 class='text-center'><a target='_'href='https://github.com/Luke-up/E-store.git' class='text-decoration-none' >Online cake store</a></h3><hr><p class='fs-6'>This project formed a part of my course at Hyperion Dev and it makes use of HTML, CSS, Javascript as well as JQuery and Bootstrap. The website has several pages showing a catalogue, home, cart and about. The website uses session storage to handle the functionality of the shopping cart. The GitHub page also contains a comprehensive readme file</p><hr><h3 class='text-center'><a target='_'href='https://github.com/Luke-up/Online_store.git' class='text-decoration-none'>Online stationary store</a></h3><hr><p class='fs-6'>This project was a part of my first Capstone project and it explores usage of CSS and Bootstrap as well as SVG's. The website is not intended to provide any functionality</p>"
}
/*The function dismisses the first view and reveals a second veiw which has more space on which to display more detailed descriptions*/
function openModal(i) {
    $("#modal").show();
    $("#welcome").hide();
    /*This will remove any previously created elements so that they are not duplicated */
    $(".removeButtons").remove();
    /*This will overwrite the title block beneath the image to indicate the current topic*/
    let firstButton = document.getElementById("currentView");
    firstButton.innerHTML = Object.keys(information)[i];
    /*This will display the actual detailed information that accompanies the topic*/
    let details = document.getElementById("details");
    details.innerHTML = Object.values(information)[i];
    /*A loop will run through the array and create buttons with which to call for the additional information */
    for (let x = 0; x < 5; x++) {
        /*If - else statement prevents a button being created for the current view */
        if (x == i) {} else {
            let row = document.getElementById("sideMenuRow");
            let newButton = document.createElement('div');
            /*The inner HTML contains the code for a button that can call this function again */
            newButton.innerHTML = "<button class='blueBlock w-100 text-center mt-3 p-3 fs-5 btn' onclick='openModal(" + x + ")'>" + Object.keys(information)[x] + "</button>";
            newButton.setAttribute("class", "col-6 removeButtons hoverColor");
            row.appendChild(newButton);
        };
    };
}
/*This is a function that will revert to the original view*/
function reset() {
    $("#modal").hide();
    $("#welcome").show();
}